import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="flex-1 py-12">
        <article className="max-w-3xl mx-auto px-6">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: April 2026
          </p>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using HypeTest (&quot;the Service&quot;), operated
              by Rekt Brands Inc., 1207 Delaware Ave, #4069, Wilmington, DE
              19806, you agree to be bound by these Terms of Service. If you do
              not agree to these terms, do not use the Service. We may update
              these terms at any time, and continued use of the Service after
              changes are posted constitutes your acceptance of the revised
              terms.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              2. Description of Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest provides AI-simulated consumer research. The Service uses
              large language models to simulate consumer responses to product
              concepts, pricing, and positioning. HypeTest does not operate real
              consumer panels, focus groups, or surveys with human participants.
              All &quot;respondents&quot; referenced in research results are
              AI-simulated personas.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              3. Research Output Disclaimer
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research results generated by HypeTest are intended for directional
              insights and hypothesis generation only. They are not a substitute
              for professional market research conducted with real human
              participants. Results have not been validated for use in high-stakes
              business decisions, including but not limited to product launches,
              large capital investments, or regulatory filings. HypeTest makes no
              guarantee of accuracy, completeness, or reliability of any
              simulated research output.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              4. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service is provided &quot;as is&quot; and &quot;as
              available&quot; without warranties of any kind, whether express or
              implied. HypeTest provides no warranty on the accuracy, relevance,
              or applicability of simulated research results. You assume all risk
              when interpreting or acting on results generated by the Service. To
              the maximum extent permitted by law, HypeTest&apos;s total
              liability to you for any claims arising from your use of the
              Service shall not exceed the total fees you have paid to HypeTest
              in the twelve (12) months preceding the claim (currently $0 for
              free-tier users).
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              5. Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain full ownership of your input data, including product
              descriptions, brand information, and research parameters that you
              submit to the Service. HypeTest retains the right to use
              anonymized, aggregated data derived from Service usage to improve
              and develop the Service. The HypeTest name, logo, and website
              content are the property of HypeTest and may not be reproduced
              without permission.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              6. Data Handling
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research inputs and results are stored in our database. Research
              result pages are publicly accessible via their unique URL. You
              should not include sensitive, confidential, or proprietary
              information in your research inputs unless you are comfortable with
              this level of accessibility. You may request deletion of your data
              by contacting us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              . For more details, see our Privacy Policy.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              7. Acceptable Use
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use the Service for any fraudulent, misleading, or
              illegal purpose. You must not present AI-simulated research results
              to third parties as real consumer research without clearly
              disclosing that the results were generated using AI-simulated
              methodology. You must not use the Service to generate content that
              is defamatory, hateful, or that violates the rights of others.
              HypeTest reserves the right to suspend or terminate access to the
              Service for violations of these terms.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              8. Third-Party References
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service and its website may reference academic research,
              publications, or methodologies from institutions and organizations
              such as Harvard Business School, Nielsen, Ipsos, McKinsey, and
              others. These references are provided for informational and
              educational purposes only and do not imply any endorsement,
              partnership, sponsorship, or affiliation between HypeTest and those
              entities.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              9. Modifications
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest reserves the right to modify, suspend, or discontinue the
              Service (or any part of it) at any time, with or without notice. We
              may update these Terms of Service at any time by posting the
              revised version on this page. Your continued use of the Service
              after any changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              10. Governing Law
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms of Service shall be governed by and construed in
              accordance with the laws of the State of Delaware, United States,
              without regard to its conflict of law provisions. Any disputes
              arising from these terms or your use of the Service shall be
              resolved in the courts of the State of Delaware.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-primary">
              11. Contact
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about these Terms of Service, please contact
              us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
