import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="flex-1 py-12">
        <article className="max-w-3xl mx-auto px-6">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: April 2026
          </p>

          <nav className="mb-8 bg-muted/30 rounded-xl p-4">
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Contents</p>
            <ol className="space-y-1 text-sm text-muted-foreground">
              <li><a href="#acceptance" className="hover:text-primary">1. Acceptance of Terms</a></li>
              <li><a href="#description" className="hover:text-primary">2. Description of Service</a></li>
              <li><a href="#disclaimer" className="hover:text-primary">3. Research Output Disclaimer</a></li>
              <li><a href="#liability" className="hover:text-primary">4. Limitation of Liability</a></li>
              <li><a href="#billing" className="hover:text-primary">5. Billing and Cancellation</a></li>
              <li><a href="#ip" className="hover:text-primary">6. Intellectual Property</a></li>
              <li><a href="#data-handling" className="hover:text-primary">7. Data Handling and Public Accessibility</a></li>
              <li><a href="#acceptable-use" className="hover:text-primary">8. Acceptable Use</a></li>
              <li><a href="#indemnification" className="hover:text-primary">9. Indemnification</a></li>
              <li><a href="#third-party" className="hover:text-primary">10. Third-Party References</a></li>
              <li><a href="#modifications" className="hover:text-primary">11. Modifications</a></li>
              <li><a href="#disputes" className="hover:text-primary">12. Dispute Resolution</a></li>
              <li><a href="#trademarks" className="hover:text-primary">13. Trademarks and Third-Party Content</a></li>
              <li><a href="#contact" className="hover:text-primary">14. Contact</a></li>
            </ol>
          </nav>

          <section className="space-y-4 mb-10">
            <h2 id="acceptance" className="text-xl font-bold text-primary">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using HypeTest (&quot;the Service&quot;), operated
              by Rekt Brands Inc., 1207 Delaware Ave, #4069, Wilmington, DE
              19806, you agree to be bound by these Terms of Service. If you do
              not agree to these terms, do not use the Service. We may update
              these terms at any time, and continued use of the Service after
              changes are posted constitutes your acceptance of the revised
              terms.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="description" className="text-xl font-bold text-primary">
              2. Description of Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest provides AI-simulated consumer research. The Service uses
              large language models to simulate consumer responses to product
              concepts, pricing, and positioning. HypeTest does not operate real
              consumer panels, focus groups, or surveys with human participants.
              All &quot;respondents&quot; referenced in research results are
              AI-simulated personas.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="disclaimer" className="text-xl font-bold text-primary">
              3. Research Output Disclaimer
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research results generated by HypeTest are intended for directional
              insights and hypothesis generation only. They are not a substitute
              for professional market research conducted with real human
              participants. Results have not been validated for use in high-stakes
              business decisions, including but not limited to product launches,
              large capital investments, or regulatory filings. HypeTest makes no
              guarantee of accuracy, completeness, or reliability of any
              simulated research output. HypeTest does not guarantee that any
              product concept, pricing strategy, name, creative, or business
              idea evaluated through the Service will succeed commercially.
              Any decisions made based on HypeTest results are made entirely
              at your own risk. HypeTest is not liable for any financial losses,
              missed opportunities, failed product launches, or other damages
              resulting from actions taken based on research outputs generated
              by the Service.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="liability" className="text-xl font-bold text-primary">
              4. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service is provided &quot;as is&quot; and &quot;as
              available&quot; without warranties of any kind, whether express or
              implied, including but not limited to warranties of merchantability,
              fitness for a particular purpose, and non-infringement. HypeTest
              provides no warranty on the accuracy, relevance, or applicability
              of simulated research results. HypeTest does not guarantee any
              specific outcome, commercial success, or return on investment from
              using the Service. You assume all risk when interpreting or acting
              on results generated by the Service. To the maximum extent
              permitted by law, HypeTest and Rekt Brands Inc. shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages, including but not limited to loss of profits,
              data, business opportunities, or goodwill, arising from your use
              of the Service. Total liability shall not exceed the greater of
              (a) the total fees you have paid to HypeTest in the twelve (12)
              months preceding the claim, or (b) $100 USD.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="billing" className="text-xl font-bold text-primary">
              5. Billing and Cancellation
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You may cancel your subscription at any time through the customer
              portal accessible from your account page, or by contacting{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              . Cancellation takes effect at the end of your current billing
              period. No prorated refunds are provided for partial billing
              periods. Upon cancellation, your account reverts to the Free plan
              and your existing research data remains accessible via existing
              links. If you believe you were charged in error, contact{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>{" "}
              within 30 days for review.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="ip" className="text-xl font-bold text-primary">
              6. Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain full ownership of your input data, including product
              descriptions, brand information, and research parameters that you
              submit to the Service. HypeTest retains the right to use
              anonymized, aggregated data derived from Service usage to improve
              and develop the Service. Anonymized means all identifying
              information (brand names, company names, specific product names,
              and user identity) is removed before any aggregated use. The
              HypeTest name, logo, and website content are the property of Rekt
              Brands Inc. and may not be reproduced without permission.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="data-handling" className="text-xl font-bold text-primary">
              7. Data Handling and Public Accessibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research inputs and results are stored in our database.{" "}
              <strong>
                Research result pages are publicly accessible to anyone with the
                unique URL.
              </strong>{" "}
              You should not include trade secrets, confidential business
              information, or sensitive proprietary data in your research inputs.
              By submitting research, you acknowledge that the results will be
              accessible via a shareable link. You may request deletion of your
              data by contacting us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              . For more details, see our Privacy Policy.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="acceptable-use" className="text-xl font-bold text-primary">
              8. Acceptable Use
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to the following when using the Service:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                You must not use the Service for any fraudulent, misleading, or
                illegal purpose.
              </li>
              <li>
                You must not present AI-simulated research results to third
                parties as real consumer research without clearly disclosing that
                the results were generated using AI-simulated methodology.
              </li>
              <li>
                You must not use research results to publicly disparage, defame,
                or mislead about competing products or brands.
              </li>
              <li>
                You must not access the Service via automated means (bots,
                scripts, scrapers) without prior written permission from Rekt
                Brands Inc.
              </li>
              <li>
                You must not resell, redistribute, or white-label the Service or
                its outputs without prior written permission.
              </li>
              <li>
                You must not use the Service to generate content that is
                defamatory, hateful, or that violates the rights of others.
              </li>
              <li>
                Each account or email is for a single individual. You must not
                share your account credentials or access with others.
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest reserves the right to suspend or terminate access to the
              Service for violations of these terms, without prior notice.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="indemnification" className="text-xl font-bold text-primary">
              9. Indemnification
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to indemnify and hold harmless Rekt Brands Inc., its
              officers, directors, employees, and agents from any claims,
              damages, losses, liabilities, or expenses (including reasonable
              attorneys&apos; fees) arising from your use of the Service,
              including but not limited to any misrepresentation of research
              results, violation of these Terms, or infringement of any third
              party&apos;s rights.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="third-party" className="text-xl font-bold text-primary">
              10. Third-Party References
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service and its website may reference academic research,
              publications, or methodologies from institutions and organizations
              such as Harvard Business School, Nielsen, Ipsos, McKinsey, and
              others. These references are provided for informational and
              educational purposes only and do not imply any endorsement,
              partnership, sponsorship, or affiliation between HypeTest and those
              entities.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="modifications" className="text-xl font-bold text-primary">
              11. Modifications
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest reserves the right to modify, suspend, or discontinue the
              Service (or any part of it) at any time, with or without notice. We
              may update these Terms of Service at any time by posting the
              revised version on this page. Your continued use of the Service
              after any changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="disputes" className="text-xl font-bold text-primary">
              12. Dispute Resolution
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Any dispute arising from these Terms or your use of the Service
              shall first be submitted to binding arbitration under the rules of
              the American Arbitration Association, conducted in Wilmington,
              Delaware. If arbitration is not permitted under applicable law, any
              disputes shall be resolved in the state or federal courts located
              in the State of Delaware. These Terms shall be governed by and
              construed in accordance with the laws of the State of Delaware,
              United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="trademarks" className="text-xl font-bold text-primary">
              13. Trademarks and Third-Party Content
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              All brand names, product names, and trademarks mentioned on this
              website or within research results (including but not limited to
              names of consumer products, research firms, and academic
              institutions) are the property of their respective owners. Their
              use on this website is for illustrative, informational, or
              comparative purposes only and does not imply any endorsement,
              sponsorship, or affiliation. Data and statistics attributed to
              third-party sources are approximate estimates based on publicly
              available information and may not reflect exact figures from those
              sources.
            </p>
          </section>

          <section className="space-y-4">
            <h2 id="contact" className="text-xl font-bold text-primary">
              14. Contact
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about these Terms of Service, please contact
              us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
