import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="flex-1 py-12">
        <article className="max-w-3xl mx-auto px-6">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-3">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: April 2026
          </p>

          <nav className="mb-8 bg-muted/30 rounded-xl p-4">
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Contents</p>
            <ol className="space-y-1 text-sm text-muted-foreground">
              <li><a href="#data-collect" className="hover:text-primary">1. Data We Collect</a></li>
              <li><a href="#data-use" className="hover:text-primary">2. How We Use Your Data</a></li>
              <li><a href="#data-storage" className="hover:text-primary">3. Data Storage and Accessibility</a></li>
              <li><a href="#data-retention" className="hover:text-primary">4. Data Retention</a></li>
              <li><a href="#third-party-services" className="hover:text-primary">5. Third-Party Services</a></li>
              <li><a href="#cookies" className="hover:text-primary">6. Cookies and Local Storage</a></li>
              <li><a href="#your-rights" className="hover:text-primary">7. Your Rights</a></li>
              <li><a href="#children" className="hover:text-primary">8. Children</a></li>
              <li><a href="#privacy-contact" className="hover:text-primary">9. Contact</a></li>
            </ol>
          </nav>

          <section className="space-y-4 mb-10">
            <p className="text-muted-foreground leading-relaxed">
              HypeTest is operated by Rekt Brands Inc., 1207 Delaware Ave,
              #4069, Wilmington, DE 19806. This Privacy Policy describes how we
              collect, use, and protect your information.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="data-collect" className="text-xl font-bold text-primary">
              1. Data We Collect
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              When you use HypeTest, we collect the following types of data:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                <strong>Contact and professional information:</strong> Your
                name, work email address, company name, job role, and company
                size, collected when you submit research.
              </li>
              <li>
                <strong>Research inputs:</strong> Product and brand descriptions,
                research parameters, target audience details, pricing
                information, and other content you submit to generate research
                results.
              </li>
              <li>
                <strong>Research results:</strong> The AI-simulated consumer
                research outputs generated by the Service.
              </li>
              <li>
                <strong>Waitlist email addresses:</strong> If you join our
                waitlist, we collect the email address you provide.
              </li>
              <li>
                <strong>IP addresses:</strong> We collect IP addresses for rate
                limiting purposes. IP addresses are stored in memory temporarily
                and are not persisted to our database.
              </li>
              <li>
                <strong>Marketing attribution data:</strong> We collect referral
                URLs and marketing attribution parameters (UTM source, medium,
                campaign) to understand how users find the Service. This data is
                stored alongside your research results.
              </li>
            </ul>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="data-use" className="text-xl font-bold text-primary">
              2. How We Use Your Data
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                To generate AI-simulated consumer research results based on your
                inputs.
              </li>
              <li>
                To send you your research report via email.
              </li>
              <li>
                To improve the Service, including refining our research
                methodology and user experience.
              </li>
              <li>
                To understand which marketing channels bring users to the
                Service.
              </li>
              <li>
                To communicate with waitlist members about product updates and
                availability.
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              We do not sell your personal data to third parties.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Our legal basis for processing personal data under GDPR:
              contractual necessity for generating and delivering research
              results you request, legitimate interest for service improvement
              and usage analytics, and consent for marketing communications and
              email notifications.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="data-storage" className="text-xl font-bold text-primary">
              3. Data Storage and Accessibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Your data is stored in Supabase, a cloud-hosted database service.{" "}
              <strong>
                Research results are accessible via unique URLs. Anyone with the
                URL can view the results.
              </strong>{" "}
              You should not include trade secrets, confidential business
              information, or sensitive proprietary data in your research inputs.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="data-retention" className="text-xl font-bold text-primary">
              4. Data Retention
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research results are retained indefinitely unless you request
              deletion. Waitlist email addresses are retained until you
              unsubscribe or request deletion. You may request deletion of your
              data at any time by contacting us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="third-party-services" className="text-xl font-bold text-primary">
              5. Third-Party Services
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We use the following third-party services to operate HypeTest:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                <strong>Supabase:</strong> Cloud database for storing research
                inputs, results, user information, and waitlist data.
              </li>
              <li>
                <strong>Vercel:</strong> Web hosting and deployment platform.
              </li>
              <li>
                <strong>Anthropic:</strong> AI model provider. Product
                descriptions and research inputs are sent to Anthropic&apos;s API
                for processing to generate simulated consumer research results.
              </li>
              <li>
                <strong>Resend:</strong> Email delivery service used to send
                research report links to your email address.
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              Each of these providers has their own privacy policies governing
              how they handle data.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Data Processing Agreements (DPAs) are in place with our
              sub-processors and are available upon request by contacting{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="cookies" className="text-xl font-bold text-primary">
              6. Cookies and Local Storage
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We use browser sessionStorage to cache research results locally for
              a better user experience. We do not use tracking cookies or
              third-party advertising scripts. We collect referral URLs and UTM
              marketing attribution parameters from the page URL when you submit
              research, to understand how users find the Service.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="your-rights" className="text-xl font-bold text-primary">
              7. Your Rights
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You may request access to, correction of, or deletion of your data
              at any time by contacting us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong>For EU residents:</strong> You have rights under the
              General Data Protection Regulation (GDPR), including the right to
              access, rectify, erase, restrict processing, and port your data.
              You also have the right to object to processing and to lodge a
              complaint with a supervisory authority.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong>For California residents:</strong> You have rights under
              the California Consumer Privacy Act (CCPA), including the right to
              know what personal information is collected, the right to request
              deletion, and the right to opt out of the sale of personal
              information. We do not sell personal information.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 id="children" className="text-xl font-bold text-primary">
              8. Children
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest is not intended for use by individuals under the age of
              18. We do not knowingly collect personal information from children.
              If you believe a child has provided us with personal data, please
              contact us and we will take steps to delete that information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 id="privacy-contact" className="text-xl font-bold text-primary">
              9. Contact
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about this Privacy Policy or wish to exercise
              your data rights, please contact us at{" "}
              <a
                href="mailto:support@hypetest.ai"
                className="text-primary underline"
              >
                support@hypetest.ai
              </a>
              .
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
