import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="flex-1 py-12">
        <article className="max-w-3xl mx-auto px-6">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-3">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: April 2026
          </p>

          <section className="space-y-4 mb-10">
            <p className="text-muted-foreground leading-relaxed">
              HypeTest is operated by Rekt Brands Inc., 1207 Delaware Ave,
              #4069, Wilmington, DE 19806. This Privacy Policy describes how we
              collect, use, and protect your information.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              1. Data We Collect
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              When you use HypeTest, we collect the following types of data:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                <strong>Research inputs:</strong> Product and brand descriptions,
                research parameters, target audience details, pricing
                information, and other content you submit to generate research
                results.
              </li>
              <li>
                <strong>Research results:</strong> The AI-simulated consumer
                research outputs generated by the Service.
              </li>
              <li>
                <strong>Email addresses:</strong> If you join our waitlist, we
                collect the email address you provide.
              </li>
              <li>
                <strong>IP addresses:</strong> We collect IP addresses for rate
                limiting purposes. IP addresses are not stored persistently or
                associated with your research data.
              </li>
            </ul>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              2. How We Use Your Data
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                To generate AI-simulated consumer research results based on your
                inputs.
              </li>
              <li>
                To improve the Service, including refining our research
                methodology and user experience.
              </li>
              <li>
                To communicate with waitlist members about product updates and
                availability.
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              We do not sell your personal data to third parties.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              3. Data Storage
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Your data is stored in Supabase, a cloud-hosted database service.
              Research results are accessible via unique URLs. Anyone with the
              URL can view the results. You should not include sensitive or
              confidential information in your research inputs.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              4. Data Retention
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Research results are retained indefinitely unless you request
              deletion. Waitlist email addresses are retained until you
              unsubscribe or request deletion. You may request deletion of your
              data at any time by contacting us at{" "}
              <a
                href="mailto:privacy@rfrekt.com"
                className="text-primary underline"
              >
                privacy@rfrekt.com
              </a>
              .
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              5. Third-Party Services
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We use the following third-party services to operate HypeTest:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground leading-relaxed">
              <li>
                <strong>Supabase:</strong> Cloud database for storing research
                inputs, results, and waitlist data.
              </li>
              <li>
                <strong>Vercel:</strong> Web hosting and deployment platform.
              </li>
              <li>
                <strong>Anthropic:</strong> AI model provider. Product
                descriptions and research inputs are sent to Anthropic&apos;s API
                for processing to generate simulated consumer research results.
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              Each of these providers has their own privacy policies governing
              how they handle data.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              6. Cookies and Local Storage
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We use browser sessionStorage to cache research results locally for
              a better user experience. We do not use tracking cookies. We do not
              use analytics tracking or third-party advertising scripts.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              7. Your Rights
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You may request access to, correction of, or deletion of your data
              at any time by contacting us at{" "}
              <a
                href="mailto:privacy@rfrekt.com"
                className="text-primary underline"
              >
                privacy@rfrekt.com
              </a>
              .
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong>For EU residents:</strong> You have rights under the
              General Data Protection Regulation (GDPR), including the right to
              access, rectify, erase, restrict processing, and port your data.
              You also have the right to object to processing and to lodge a
              complaint with a supervisory authority.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong>For California residents:</strong> You have rights under
              the California Consumer Privacy Act (CCPA), including the right to
              know what personal information is collected, the right to request
              deletion, and the right to opt out of the sale of personal
              information. We do not sell personal information.
            </p>
          </section>

          <section className="space-y-4 mb-10">
            <h2 className="text-xl font-bold text-primary">
              8. Children
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              HypeTest is not intended for use by individuals under the age of
              18. We do not knowingly collect personal information from children.
              If you believe a child has provided us with personal data, please
              contact us and we will take steps to delete that information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-primary">
              9. Contact
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about this Privacy Policy or wish to exercise
              your data rights, please contact us at{" "}
              <a
                href="mailto:privacy@rfrekt.com"
                className="text-primary underline"
              >
                privacy@rfrekt.com
              </a>
              .
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
